export enum actionTypes {
  BUY_CAKE = "BUY_CAKE",
  BUY_ICECREAM = "BUY_ICECREAM",
  FETCH_USER_REQUEST = "FETCH_USER_REQUEST",
  FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS",
  FETCH_USER_FAILURE = "FETCH_USER_FAILURE",
}
